name: Bug Report
description: Report a bug or unexpected behavior in go-assern
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Before submitting, please:
        1. **Check the latest release** — Confirm the bug exists in the latest stable release
        2. **Check the nightly build** — Test against nightly to see if it's already fixed
        3. If the bug only exists in the stable release but is fixed in nightly, no need to report it

  - type: input
    id: version
    attributes:
      label: Version
      description: "Output of `assern version`"
      placeholder: "v0.x.x"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux (AMD64)
        - Linux (ARM64)
        - Windows (WSL2)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug
      placeholder: "Describe what happened..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Run `assern ...`
        2. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: "Paste any relevant logs or error output. Run with `--verbose` for more detail."
      render: shell
    validations:
      required: false
